# Generated by Django 4.1 on 2022-10-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0003_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no-profile-photo.png', upload_to=''),
        ),
    ]
