# Generated by Django 4.1 on 2022-10-14 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialMedia', '0010_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='avatares'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('', '-----'), ('Argentina', 'Argentina'), ('Belice', 'Belice'), ('Bolivia', 'Bolivia'), ('Brasil', 'Brasil'), ('Canada', 'Canada'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Curazao', 'Curazao'), ('Aruba', 'Aruba'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Guatemala', 'Guatemala'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Jamaica', 'Jamaica'), ('Mexico', 'Mexico'), ('Nicaragua', 'Nicaragua'), ('Panama', 'Panama'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Puerto Rico', 'Puerto Rico'), ('Republica Dominicana', 'Republica Dominicana'), ('United States', 'United States'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
